id: IBE9ED2D7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-20T08:08:05+00:00'
last_modified: '2022-06-14T08:24:50.661673+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN21540
  title: གྲགས་ཆེན་བཅོ་བརྒྱད། ༼༡-༧༽
  author: ''
  base:
    E99C:
      image_group_id: I3CN21757
      title: ''
      total_pages: ''
      order: 1
      base_file: E99C.txt
    EBBF:
      image_group_id: I3CN21758
      title: ''
      total_pages: ''
      order: 2
      base_file: EBBF.txt
    7C1E:
      image_group_id: I3CN21759
      title: ''
      total_pages: ''
      order: 3
      base_file: 7C1E.txt
    3CF1:
      image_group_id: I3CN21760
      title: ''
      total_pages: ''
      order: 4
      base_file: 3CF1.txt
    ACD5:
      image_group_id: I3CN21761
      title: ''
      total_pages: ''
      order: 5
      base_file: ACD5.txt
    0394:
      image_group_id: I3CN21762
      title: ''
      total_pages: ''
      order: 6
      base_file: 0394.txt
    B291:
      image_group_id: I3CN21763
      title: ''
      total_pages: ''
      order: 7
      base_file: B291.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
